dist: trusty
sudo: required
language: C++

matrix:
  include:

    - addons:
        postgresql: 9.2
        apt:
          packages:
            - postgresql-server-dev-9.2
            - postgresql-9.2-pgtap
      env:
        - POSTGRESQL=9.2

    - addons:
        postgresql: 9.3
        apt:
          packages:
            - postgresql-server-dev-9.3
            - postgresql-9.3-pgtap
      env:
        - POSTGRESQL=9.3

    - addons:
        postgresql: 9.4
        apt:
          packages:
            - postgresql-server-dev-9.4
            - postgresql-9.4-pgtap
      env:
        - POSTGRESQL=9.4

    - addons:
        postgresql: 9.5
        apt:
          packages:
            - postgresql-server-dev-9.5
            - postgresql-9.5-pgtap
      env:
        - POSTGRESQL=9.5

    - addons:
        postgresql: 9.6
        apt:
          packages:
            - postgresql-server-dev-9.6
            - postgresql-9.6-pgtap
      env:
        - POSTGRESQL=9.6


before_install:
  # These are needed to test Debian package build
  - sudo apt-get install debhelper fakeroot postgresql-server-dev-all

script:
  - make
  - sudo make install
  - make installcheck || { cat regression.diffs; false; }

  # Test upgrades from all tagged versions
  - test/ci/test_all_upgrades.sh

  # Test build and install from package
  - PG_SUPPORTED_VERSIONS=${POSTGRESQL} make deb
