sudo: false
language: C++
services:
  - postgresql: "9.4"
addons:
  apt:
    packages:
    - postgresql-9.4
    - postgresql-server-dev-9.4
script:
  - make
  - make install
  - make installcheck || { cat regression.diffs; false; }
