---

dist: bionic
sudo: required
language: C++

env:
  matrix:
    - PG=9.3
    - PG=9.4
    - PG=9.5
    - PG=9.6
    - PG=10
    - PG=11

before_install:
  - sudo apt-get -y --purge remove postgresql libpq-dev libpq5
    postgresql-client-common postgresql-common
  - sudo rm -rf /var/lib/postgresql
  - sudo apt-get update -qq
  - sudo apt-get install -y
    postgresql-${PG}
    postgresql-client-${PG}
    postgresql-${PG}-pgtap
    postgresql-server-dev-${PG}
    postgresql-server-dev-all
    debhelper fakeroot
    libtap-parser-sourcehandler-pgtap-perl
  # Set PATH as postgresql-server-dev-all pretends version is 11
  - export PATH=/usr/lib/postgresql/${PG}/bin:${PATH}

before_script:
  - sudo -u postgres createuser -s "$USER"
  - sudo -u postgres createuser -s root

notifications:
  # LINZ corporate email server is dropping messages from Travis
  # see: https://github.com/linz/LI-tasks/issues/14
  email:
    - jeremy.palmer.nz@gmail.com
    - ivan.mincik@gmail.com

script:
  - make
  # Pre-install tests
  - make check
  # Install
  - sudo env "PATH=$PATH" make install
  # Post-install tests
  - make installcheck || { cat regression.diffs; false; }
  - make installcheck-loader || { cat regression.diffs; false; }
  - make installcheck-loader-noext || { cat regression.diffs; false; }
  # Packaging tests
  - make dist

  # Test upgrades from all tagged versions
  - test/ci/test_all_upgrades.sh

  # Test build and install from package
  - PG_SUPPORTED_VERSIONS=${PG} make deb
  - sudo dpkg -i ../*-dbpatch_*.deb
  - make deb
  - make deb-check

# vim: set ts=2 sts=2 sw=2 et:

