---

dist: trusty
sudo: required
language: C++

matrix:
  include:

    - addons:
        postgresql: 9.3
        apt:
          packages:
            - postgresql-9.3-pgtap
      env:
        - POSTGRESQL=9.3

    - addons:
        postgresql: 9.4
        apt:
          packages:
            - postgresql-9.4-pgtap
      env:
        - POSTGRESQL=9.4

    - addons:
        postgresql: 9.5
        apt:
          packages:
            - postgresql-9.5-pgtap
      env:
        - POSTGRESQL=9.5

    - addons:
        postgresql: 9.6
        apt:
          packages:
            - postgresql-9.6-pgtap
      env:
        - POSTGRESQL=9.6

    - addons:
        postgresql: 10
        apt:
          packages:
            - postgresql-10-pgtap
      env:
        - POSTGRESQL=10


before_install:
  # These are needed to test Debian package build
  - sudo apt-get install debhelper fakeroot
    postgresql-server-dev-9.2
    postgresql-server-dev-all
    libtap-parser-sourcehandler-pgtap-perl

script:
  - make
  # Set PGPORT
  - export PGPORT=`pg_lsclusters  | grep ' online ' | tail -1 | awk '{print $3}'`
  # Pre-install tests
  - make check
  # Install
  - sudo env "PATH=$PATH" make install
  # Post-install tests
  - make installcheck || { cat regression.diffs; false; }
  - make installcheck-loader || { cat regression.diffs; false; }
  - make installcheck-loader-noext || { cat regression.diffs; false; }
  # Packaging tests
  - make dist

  # Test upgrades from all tagged versions
  - test/ci/test_all_upgrades.sh

  # Test build and install from package
  - PG_SUPPORTED_VERSIONS=${POSTGRESQL} make deb
  - sudo dpkg -i ../postgresql-${POSTGRESQL}-dbpatch_*.deb
