name: Test

on:
  pull_request:
    branches-ignore:
      - packagecloud
      - 'release-*'
  push:
    branches:
      - master
      - packagecloud
      - 'release-*'
    tags-ignore:
      - 'debian/*'
  schedule:
    - cron: '0 12 * * 0'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Run pre-commit hooks
        run: nix-shell --pure --run 'pre-commit run --all-files'

  test-source:
    name: Test PostgreSQL ${{ matrix.pg }} source install on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        pg: ['10', '12', '14']
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
    env:
      # Set PATH as postgresql-server-dev-all pretends version is 11
      PATH: /usr/lib/postgresql/${{ matrix.pg }}/bin:/bin:/usr/bin:/usr/local/bin
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Remove conflicting packages
        run: |
          sudo apt-get --assume-yes --purge remove \
            libpq5 \
            libpq-dev \
            php*fpm \
            postgresql \
            postgresql-client-common \
            postgresql-common

      - name: Remove PostgreSQL install files
        run: sudo rm --force --recursive /var/lib/postgresql

      - name: Update package database
        run: sudo apt-get update

      - name: Install setup dependencies
        run: sudo apt-get --assume-yes install curl ca-certificates gnupg

      - name: Trust PostgreSQL repository key
        run: curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

      - name: Get release codename
        id: distro
        run: echo "::set-output name=codename::$(lsb_release --codename --short)"

      - name: Add PostgreSQL APT repo
        run:
          echo "deb http://apt.postgresql.org/pub/repos/apt/ ${{ steps.distro.outputs.codename
          }}-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list

      - name: Update package database with PostgreSQL repo
        run: sudo apt-get update

      - name: Install test dependencies
        run: |
          sudo apt-get install --assume-yes \
            debhelper \
            fakeroot \
            libtap-parser-sourcehandler-pgtap-perl \
            postgresql-client-${{ matrix.pg }} \
            postgresql-${{ matrix.pg }} \
            postgresql-${{ matrix.pg }}-pgtap \
            postgresql-server-dev-all \
            postgresql-server-dev-${{ matrix.pg }}

      - name: Setup current user as PostgreSQL superuser
        run: sudo --user=postgres createuser --superuser "$USER"

      - name: Setup PostgreSQL root user
        run: sudo --user=postgres createuser --superuser root

      - name: Build
        run: make

      - name: Test build
        run: make check

      - name: Install
        run: sudo env "PATH=$PATH" make install

      - name: Test installation
        run: make installcheck || { cat regression.diffs; false; }

      - name: Test loader
        run: make installcheck-loader || { cat regression.diffs; false; }

      - name: Test loader without extension
        run: make installcheck-loader-noext || { cat regression.diffs; false; }

      - name: Test upgrades from all tagged versions
        run: sudo env "PATH=$PATH" test/ci/test_all_upgrades.bash

      - name: Uninstall
        run: sudo make uninstall

  test-source-without-git-metadata:
    name: Test PostgreSQL ${{ matrix.pg }} source install without Git metadata on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        pg: ['14']
        os: [ubuntu-22.04]
    env:
      # Set PATH as postgresql-server-dev-all pretends version is 11
      PATH: /usr/lib/postgresql/${{ matrix.pg }}/bin:/bin:/usr/bin:/usr/local/bin
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Remove conflicting packages
        run: |
          sudo apt-get --assume-yes --purge remove \
            libpq5 \
            libpq-dev \
            php*fpm \
            postgresql \
            postgresql-client-common \
            postgresql-common

      - name: Remove PostgreSQL install files
        run: sudo rm --force --recursive /var/lib/postgresql

      - name: Update package database
        run: sudo apt-get update

      - name: Install setup dependencies
        run: sudo apt-get --assume-yes install curl ca-certificates gnupg

      - name: Trust PostgreSQL repository key
        run: curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

      - name: Get release codename
        id: distro
        run: echo "::set-output name=codename::$(lsb_release --codename --short)"

      - name: Add PostgreSQL APT repo
        run:
          echo "deb http://apt.postgresql.org/pub/repos/apt/ ${{ steps.distro.outputs.codename
          }}-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list

      - name: Update package database with PostgreSQL repo
        run: sudo apt-get update

      - name: Install test dependencies
        run: |
          sudo apt-get install --assume-yes \
            debhelper \
            fakeroot \
            libtap-parser-sourcehandler-pgtap-perl \
            postgresql-client-${{ matrix.pg }} \
            postgresql-${{ matrix.pg }} \
            postgresql-${{ matrix.pg }}-pgtap \
            postgresql-server-dev-all \
            postgresql-server-dev-${{ matrix.pg }}

      - name: Setup current user as PostgreSQL superuser
        run: sudo --user=postgres createuser --superuser "$USER"

      - name: Setup PostgreSQL root user
        run: sudo --user=postgres createuser --superuser root

      - name: Remove Git metadata
        run: rm --recursive .git

      - name: Install
        run: sudo env "PATH=$PATH" make install

      - name: Test installation
        run: make installcheck || { cat regression.diffs; false; }

      - name: Test loader
        run: make installcheck-loader || { cat regression.diffs; false; }

      - name: Test loader without extension
        run: make installcheck-loader-noext || { cat regression.diffs; false; }

      - name: Uninstall
        run: sudo make uninstall

  test-package:
    name: Test PostgreSQL ${{ matrix.pg }} package install on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        pg: ['10', '12', '14']
        include:
          - os: ubuntu-18.04
            release: bionic
          - os: ubuntu-20.04
            release: focal
          - os: ubuntu-22.04
            release: jammy
          - os: ubuntu-latest
            release: jammy
    env:
      # Set PATH as postgresql-server-dev-all pretends version is 11
      PATH: /usr/lib/postgresql/${{ matrix.pg }}/bin:/bin:/usr/bin:/usr/local/bin
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Remove conflicting packages
        run: |
          sudo apt-get --assume-yes --purge remove \
            libpq5 \
            libpq-dev \
            php*fpm \
            postgresql \
            postgresql-client-common \
            postgresql-common

      - name: Remove PostgreSQL install files
        run: sudo rm --force --recursive /var/lib/postgresql

      - name: Update package database
        run: sudo apt-get update

      - name: Install setup dependencies
        run: sudo apt-get --assume-yes install curl ca-certificates gnupg

      - name: Trust PostgreSQL repository key
        run: curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

      - name: Get release codename
        id: distro
        run: echo "::set-output name=codename::$(lsb_release --codename --short)"

      - name: Add PostgreSQL APT repo
        run:
          echo "deb http://apt.postgresql.org/pub/repos/apt/ ${{ steps.distro.outputs.codename
          }}-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list

      - name: Update package database with PostgreSQL repo
        run: sudo apt-get update

      - name: Install test dependencies
        run: |
          sudo apt-get install --assume-yes \
            debhelper \
            fakeroot \
            libtap-parser-sourcehandler-pgtap-perl \
            postgresql-client-${{ matrix.pg }} \
            postgresql-${{ matrix.pg }} \
            postgresql-${{ matrix.pg }}-pgtap \
            postgresql-server-dev-all \
            postgresql-server-dev-${{ matrix.pg }}

      - name: Setup current user as PostgreSQL superuser
        run: sudo --user=postgres createuser --superuser "$USER"

      - name: Setup PostgreSQL root user
        run: sudo --user=postgres createuser --superuser root

      - name: Build local debian package
        uses: linz/linz-software-repository@v12
        with:
          release: ${{ matrix.release }}
        env:
          PG_SUPPORTED_VERSIONS: ${{ matrix.pg }}

      - name: Install PostgreSQL-agnostic package
        run: sudo dpkg --install build-area/dbpatch_*.deb

      - name: Show package contents
        run: dpkg -L dbpatch

      - name: Run post-install PostgreSQL-agnostic tests
        run: make installcheck-loader-noext || { cat regression.diffs; false; }

      - name: Install PostgreSQL-specific dbpatch package
        run: sudo dpkg --install build-area/postgresql-${{ matrix.pg }}-dbpatch_*.deb

      - name: Test installation
        run: make installcheck || { cat regression.diffs; false; }

      - name: Test loader
        run: make installcheck-loader || { cat regression.diffs; false; }

      - name: Build packages for all supported versions
        uses: linz/linz-software-repository@v12
        with:
          release: ${{ matrix.release }}

      - name: Test package
        run: make deb-check

  package:
    needs:
      - lint
      - test-source
      - test-source-without-git-metadata
      - test-package
    name: Package for Debian
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        release:
          - bionic
          - focal
          - jammy
      max-parallel: 1

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine packagecloud publication target
        run: |
          # TODO: it would be nice to turn this into a single-liner in
          #       github-action syntax
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub event_name: ${{ github.event_name }}"
          REPO=
          if test "${{ github.event_name }}" = 'push'; then
            if expr "${{ github.ref }}" : "refs/tags/" > /dev/null; then
              REPO=test
              git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
            elif test "${{ github.ref }}" = 'refs/heads/packagecloud' \
                   -o "${{ github.ref }}" = 'refs/heads/master'
            then
              REPO=dev
            fi
          fi
          echo "REPO=$REPO" | tee --append $GITHUB_ENV

      - name: Build and upload to packagecloud
        uses: linz/linz-software-repository@v12
        with:
          release: ${{ matrix.release }}
          packagecloud_token: ${{ secrets.LINZCI_PACKAGECLOUD_TOKEN }}
          packagecloud_repository: ${{ env.REPO }}
          push_to_git_remote: origin

  finalise:
    if: always()
    needs:
      - lint
      - test-source
      - test-source-without-git-metadata
      - test-package
      - package
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
